version: '3.8'

services:

  vpn-tun:
    image: ghcr.io/sagernet/sing-box:v1.13.14 #1.13.14 # latest
    container_name: vpn-tun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./vpn/config.json:/etc/sing-box/config.json
    command: run -c /etc/sing-box/config.json
    ports:
      - "8080:80"  # Теперь порт 80 бота будет доступен на 8080 хоста
    networks:
      - total_network 

  postgres:
    image: postgres:14.13
    container_name: app_postgres_v14
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Moscow
    ports:
      - "127.0.0.1:25432:5432"
    volumes:
      - postgres_data_v14:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - total_network  # <-- Посадили в ту же сеть, что и VPN

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    restart: always
    env_file: .env  # Docker Compose сам прочитает файл и прокинет ВСЕ переменные внутрь
    environment:
      POSTGRES_HOST: postgres  # Будет работать идеально, т.к. VPN-контейнер видит этот хост
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Moscow
    network_mode: "service:vpn-tun"  # Забираем сеть у VPN
    depends_on:
      - vpn-tun
      - postgres  # <-- Объединили depends_on и указали правильное имя сервиса базы
    # volumes:
    #   - ./master/session_name.session:/masterapp/session_name.session
    #   - /etc/localtime:/etc/localtime:ro
    # volumes:
    #   # Монтируем файлы сессии из корня твоего проекта прямо в рабочую директорию бота (/workspace)
    #   - ./repair_desk_bot.session:/workspace/repair_desk_bot.session
    #   - ./repair_desk_bot.session-journal:/workspace/repair_desk_bot.session-journal
    #   # Синхронизация времени
    #   - /etc/localtime:/etc/localtime:ro
    volumes:
        #- .:/workspace # Монтируем ВСЮ текущую папку проекта в /workspace контейнера
        - ./repair_desk_bot.session:/workspace/repair_desk_bot.session
        - ./repair_desk_bot.session-journal:/workspace/repair_desk_bot.session-journal
        - /etc/localtime:/etc/localtime:ro



volumes:
  postgres_data_v14:

networks:
  total_network:  # Одна чистая сеть для всех
    driver: bridge


  




# version: '3.8'

# services:

#   postgres:
#     image: postgres:14.13 #latest  !15.6
#     container_name: app_postgres_v14
#     environment:
#       POSTGRES_USER: ${USER_DB}
#       POSTGRES_PASSWORD: ${PASSWORD_DB}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       # Меняем порт хоста на 25432, если порт 5432 занят локальной БД
#       - "127.0.0.1:25432:5432"
#     volumes:
#       - postgres_data_v14:/var/lib/postgresql/data
#     networks:
#       - db-network

#   bot:
#       build:
#         context: .
#         dockerfile: Dockerfile.bot
#       container_name: telegram_bot
#       environment:
#         POSTGRES_HOST: postgres
#         POSTGRES_USER: ${USER_DB}
#         POSTGRES_PASSWORD: ${PASSWORD_DB}
#         POSTGRES_DB: ${POSTGRES_DB}
#       depends_on:
#         - postgres
#       networks:
#         - db-network
#       ports:
#         - "8080:80"  # Публикация порта 80 контейнера на порт 8080 хоста

# volumes:
#   postgres_data_v14:

# networks:
#   db-network:
#     driver: bridge